[2023-07-29 03:37:55,520] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:33:44.992964+00:00 [queued]>
[2023-07-29 03:37:55,539] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:33:44.992964+00:00 [queued]>
[2023-07-29 03:37:55,542] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:37:55,544] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-07-29 03:37:55,546] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:37:55,575] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_threshold> on 2023-07-29 03:33:44.992964+00:00
[2023-07-29 03:37:55,583] {standard_task_runner.py:52} INFO - Started process 9003 to run task
[2023-07-29 03:37:55,598] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'verificar_threshold', 'manual__2023-07-29T03:33:44.992964+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpehrebjkp', '--error-file', '/tmp/tmpp5ow8vly']
[2023-07-29 03:37:55,605] {standard_task_runner.py:80} INFO - Job 111: Subtask verificar_threshold
[2023-07-29 03:37:55,759] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:33:44.992964+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 03:37:55,928] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=verificar_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T03:33:44.992964+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T03:33:44.992964+00:00
[2023-07-29 03:37:55,971] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 03:37:59,372] {logging_mixin.py:115} INFO - Fallo:  local variable 'message' referenced before assignment
[2023-07-29 03:37:59,375] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_paises.py", line 68, in verificar_threshold
    enviar_alerta(city, categoria_nombre, categoria, min_t, max_t, is_under_threshold=False)
  File "/opt/airflow/dags/script_etl.py", line 131, in enviar_alerta
    raise exception
  File "/opt/airflow/dags/script_etl.py", line 124, in enviar_alerta
    message = message.encode('utf-8')
UnboundLocalError: local variable 'message' referenced before assignment
[2023-07-29 03:37:59,408] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_etl_paises, task_id=verificar_threshold, execution_date=20230729T033344, start_date=20230729T033755, end_date=20230729T033759
[2023-07-29 03:37:59,434] {standard_task_runner.py:97} ERROR - Failed to execute job 111 for task verificar_threshold (local variable 'message' referenced before assignment; 9003)
[2023-07-29 03:37:59,469] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-29 03:37:59,546] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
