[2023-07-29 03:39:01,103] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:33:44.992964+00:00 [queued]>
[2023-07-29 03:39:01,122] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:33:44.992964+00:00 [queued]>
[2023-07-29 03:39:01,124] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:39:01,126] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-07-29 03:39:01,129] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:39:01,159] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_threshold> on 2023-07-29 03:33:44.992964+00:00
[2023-07-29 03:39:01,167] {standard_task_runner.py:52} INFO - Started process 9072 to run task
[2023-07-29 03:39:01,179] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'verificar_threshold', 'manual__2023-07-29T03:33:44.992964+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpndxzphee', '--error-file', '/tmp/tmpaqehennb']
[2023-07-29 03:39:01,183] {standard_task_runner.py:80} INFO - Job 112: Subtask verificar_threshold
[2023-07-29 03:39:01,320] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:33:44.992964+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 03:39:01,495] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=verificar_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T03:33:44.992964+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T03:33:44.992964+00:00
[2023-07-29 03:39:01,532] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 03:39:04,012] {logging_mixin.py:115} INFO - Fallo:  local variable 'message' referenced before assignment
[2023-07-29 03:39:04,016] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_paises.py", line 68, in verificar_threshold
    enviar_alerta(city, categoria_nombre, categoria, min_t, max_t, is_under_threshold=False)
  File "/opt/airflow/dags/script_etl.py", line 131, in enviar_alerta
    raise exception
  File "/opt/airflow/dags/script_etl.py", line 124, in enviar_alerta
    message = message.encode('utf-8')
UnboundLocalError: local variable 'message' referenced before assignment
[2023-07-29 03:39:04,112] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_etl_paises, task_id=verificar_threshold, execution_date=20230729T033344, start_date=20230729T033901, end_date=20230729T033904
[2023-07-29 03:39:04,154] {standard_task_runner.py:97} ERROR - Failed to execute job 112 for task verificar_threshold (local variable 'message' referenced before assignment; 9072)
[2023-07-29 03:39:04,234] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-29 03:39:04,361] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
