[2023-07-25 22:30:16,246] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla_ scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-25 22:30:16,602] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla_ scheduled__2023-07-12T00:00:00+00:00 [queued]>
[2023-07-25 22:30:16,621] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:30:16,643] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 22:30:16,661] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:30:17,103] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): crear_tabla_> on 2023-07-12 00:00:00+00:00
[2023-07-25 22:30:17,226] {standard_task_runner.py:52} INFO - Started process 217 to run task
[2023-07-25 22:30:17,531] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'crear_tabla_', 'scheduled__2023-07-12T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmp3vocw4vl', '--error-file', '/tmp/tmptz9qexos']
[2023-07-25 22:30:17,580] {standard_task_runner.py:80} INFO - Job 27: Subtask crear_tabla_
[2023-07-25 22:30:21,746] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.crear_tabla_ scheduled__2023-07-12T00:00:00+00:00 [running]> on host 484a5a9deba0
[2023-07-25 22:30:25,725] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=crear_tabla_
AIRFLOW_CTX_EXECUTION_DATE=2023-07-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-12T00:00:00+00:00
[2023-07-25 22:30:25,986] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-25 22:30:27,174] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  database "bapintor_coderhouse" does not exist

[2023-07-25 22:30:27,427] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_con_conexion_postgres, task_id=crear_tabla_, execution_date=20230712T000000, start_date=20230725T223016, end_date=20230725T223027
[2023-07-25 22:30:28,172] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task crear_tabla_ (connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  database "bapintor_coderhouse" does not exist
; 217)
[2023-07-25 22:30:28,515] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 22:30:29,902] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
