[2023-07-25 22:30:53,075] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla_ scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-25 22:30:53,263] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla_ scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-25 22:30:53,265] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:30:53,270] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 22:30:53,275] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:30:53,561] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): crear_tabla_> on 2023-07-21 00:00:00+00:00
[2023-07-25 22:30:53,607] {standard_task_runner.py:52} INFO - Started process 249 to run task
[2023-07-25 22:30:53,641] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'crear_tabla_', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpgdz2q595', '--error-file', '/tmp/tmpyc7qvsnj']
[2023-07-25 22:30:53,654] {standard_task_runner.py:80} INFO - Job 36: Subtask crear_tabla_
[2023-07-25 22:30:54,440] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.crear_tabla_ scheduled__2023-07-21T00:00:00+00:00 [running]> on host 484a5a9deba0
[2023-07-25 22:30:55,068] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=crear_tabla_
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-21T00:00:00+00:00
[2023-07-25 22:30:55,143] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-25 22:30:56,038] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 204, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  database "bapintor_coderhouse" does not exist

[2023-07-25 22:30:56,057] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_con_conexion_postgres, task_id=crear_tabla_, execution_date=20230721T000000, start_date=20230725T223053, end_date=20230725T223056
[2023-07-25 22:30:56,165] {standard_task_runner.py:97} ERROR - Failed to execute job 36 for task crear_tabla_ (connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  database "bapintor_coderhouse" does not exist
; 249)
[2023-07-25 22:30:56,218] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 22:30:56,374] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
