[2023-07-26 22:25:42,356] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T22:25:20.070108+00:00 [queued]>
[2023-07-26 22:25:42,374] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T22:25:20.070108+00:00 [queued]>
[2023-07-26 22:25:42,376] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 22:25:42,378] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 22:25:42,380] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 22:25:42,407] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_datos> on 2023-07-26 22:25:20.070108+00:00
[2023-07-26 22:25:42,420] {standard_task_runner.py:52} INFO - Started process 2123 to run task
[2023-07-26 22:25:42,432] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'transformar_datos', 'manual__2023-07-26T22:25:20.070108+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmp3f_myt5i', '--error-file', '/tmp/tmpqbia5rqi']
[2023-07-26 22:25:42,435] {standard_task_runner.py:80} INFO - Job 109: Subtask transformar_datos
[2023-07-26 22:25:42,563] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T22:25:20.070108+00:00 [running]> on host 484a5a9deba0
[2023-07-26 22:25:42,959] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=transformar_datos
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T22:25:20.070108+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-26T22:25:20.070108+00:00
[2023-07-26 22:28:26,693] {logging_mixin.py:115} INFO - name         city  Housing  ... Outdoors               process_date
0          Aarhus  #f3c32c  ...  #f1351b 2023-07-26 22:28:26.462660
1          Aarhus   6.1315  ...     4.13 2023-07-26 22:28:26.462660
2        Adelaide  #f3c32c  ...  #f1351b 2023-07-26 22:28:26.462660
3        Adelaide   6.3095  ...    5.531 2023-07-26 22:28:26.462660
4     Albuquerque  #f3c32c  ...  #f1351b 2023-07-26 22:28:26.462660
..            ...      ...  ...      ...                        ...
527       Yerevan   9.6945  ...   7.7765 2023-07-26 22:28:26.462660
528        Zagreb  #f3c32c  ...  #f1351b 2023-07-26 22:28:26.462660
529        Zagreb     8.91  ...    4.809 2023-07-26 22:28:26.462660
530        Zurich  #f3c32c  ...  #f1351b 2023-07-26 22:28:26.462660
531        Zurich    1.473  ...    5.401 2023-07-26 22:28:26.462660

[532 rows x 19 columns]
[2023-07-26 22:28:28,049] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script_etl.py", line 81, in transform_data
    cursor.execute(insert_query, values)
IndexError: list index out of range
[2023-07-26 22:28:28,194] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_con_conexion_postgres, task_id=transformar_datos, execution_date=20230726T222520, start_date=20230726T222542, end_date=20230726T222828
[2023-07-26 22:28:28,245] {standard_task_runner.py:97} ERROR - Failed to execute job 109 for task transformar_datos (list index out of range; 2123)
[2023-07-26 22:28:28,301] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 22:28:28,456] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
