[2023-07-29 02:22:12,638] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:16:58.650270+00:00 [queued]>
[2023-07-29 02:22:12,699] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:16:58.650270+00:00 [queued]>
[2023-07-29 02:22:12,704] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 02:22:12,705] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-07-29 02:22:12,712] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 02:22:12,742] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_threshold> on 2023-07-29 02:16:58.650270+00:00
[2023-07-29 02:22:12,751] {standard_task_runner.py:52} INFO - Started process 4240 to run task
[2023-07-29 02:22:12,762] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'verificar_threshold', 'manual__2023-07-29T02:16:58.650270+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmp7gdw3s_y', '--error-file', '/tmp/tmpybuvw6ac']
[2023-07-29 02:22:12,766] {standard_task_runner.py:80} INFO - Job 87: Subtask verificar_threshold
[2023-07-29 02:22:12,896] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:16:58.650270+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 02:22:13,102] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=verificar_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T02:16:58.650270+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T02:16:58.650270+00:00
[2023-07-29 02:22:13,128] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 02:22:15,928] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_paises.py", line 44, in verificar_threshold
    with open('config.json', 'r') as json_config:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[2023-07-29 02:22:15,948] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_etl_paises, task_id=verificar_threshold, execution_date=20230729T021658, start_date=20230729T022212, end_date=20230729T022215
[2023-07-29 02:22:15,973] {standard_task_runner.py:97} ERROR - Failed to execute job 87 for task verificar_threshold ([Errno 2] No such file or directory: 'config.json'; 4240)
[2023-07-29 02:22:16,030] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-29 02:22:16,123] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
