[2023-07-29 03:20:33,770] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:15:26.898852+00:00 [queued]>
[2023-07-29 03:20:33,789] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:15:26.898852+00:00 [queued]>
[2023-07-29 03:20:33,791] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:20:33,794] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-07-29 03:20:33,796] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:20:33,826] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_threshold> on 2023-07-29 03:15:26.898852+00:00
[2023-07-29 03:20:33,835] {standard_task_runner.py:52} INFO - Started process 7870 to run task
[2023-07-29 03:20:33,847] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'verificar_threshold', 'manual__2023-07-29T03:15:26.898852+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpyuuh_rd2', '--error-file', '/tmp/tmpdbk3acap']
[2023-07-29 03:20:33,850] {standard_task_runner.py:80} INFO - Job 102: Subtask verificar_threshold
[2023-07-29 03:20:33,973] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:15:26.898852+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 03:20:34,119] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=verificar_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T03:15:26.898852+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T03:15:26.898852+00:00
[2023-07-29 03:20:34,148] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 03:20:35,199] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_paises.py", line 42, in verificar_threshold
    for city, categories in thresholds.items():
UnboundLocalError: local variable 'thresholds' referenced before assignment
[2023-07-29 03:20:35,225] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_etl_paises, task_id=verificar_threshold, execution_date=20230729T031526, start_date=20230729T032033, end_date=20230729T032035
[2023-07-29 03:20:35,262] {standard_task_runner.py:97} ERROR - Failed to execute job 102 for task verificar_threshold (local variable 'thresholds' referenced before assignment; 7870)
[2023-07-29 03:20:35,327] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-29 03:20:35,425] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
