[2023-07-26 18:08:23,289] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T18:08:03.341752+00:00 [queued]>
[2023-07-26 18:08:23,328] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T18:08:03.341752+00:00 [queued]>
[2023-07-26 18:08:23,458] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 18:08:23,460] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 18:08:23,461] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 18:08:23,739] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_datos> on 2023-07-26 18:08:03.341752+00:00
[2023-07-26 18:08:23,780] {standard_task_runner.py:52} INFO - Started process 306 to run task
[2023-07-26 18:08:23,959] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'transformar_datos', 'manual__2023-07-26T18:08:03.341752+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpxl1uk1u0', '--error-file', '/tmp/tmp_8lt2z96']
[2023-07-26 18:08:23,964] {standard_task_runner.py:80} INFO - Job 97: Subtask transformar_datos
[2023-07-26 18:08:24,423] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T18:08:03.341752+00:00 [running]> on host 484a5a9deba0
[2023-07-26 18:08:24,882] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=transformar_datos
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T18:08:03.341752+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-26T18:08:03.341752+00:00
[2023-07-26 18:09:56,025] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-26 18:09:56,029] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script_etl.py", line 70, in transform_data
    cursor = connection.cursor()
AttributeError: 'Connection' object has no attribute 'cursor'
[2023-07-26 18:09:56,051] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_con_conexion_postgres, task_id=transformar_datos, execution_date=20230726T180803, start_date=20230726T180823, end_date=20230726T180956
[2023-07-26 18:09:56,084] {standard_task_runner.py:97} ERROR - Failed to execute job 97 for task transformar_datos ('Connection' object has no attribute 'cursor'; 306)
[2023-07-26 18:09:56,139] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 18:09:56,221] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
