[2023-07-29 03:29:03,531] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:23:39.066269+00:00 [queued]>
[2023-07-29 03:29:03,550] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:23:39.066269+00:00 [queued]>
[2023-07-29 03:29:03,553] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:29:03,555] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-07-29 03:29:03,557] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 03:29:03,588] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_threshold> on 2023-07-29 03:23:39.066269+00:00
[2023-07-29 03:29:03,596] {standard_task_runner.py:52} INFO - Started process 8412 to run task
[2023-07-29 03:29:03,607] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'verificar_threshold', 'manual__2023-07-29T03:23:39.066269+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmppdmscuwc', '--error-file', '/tmp/tmpk2_wq7r9']
[2023-07-29 03:29:03,611] {standard_task_runner.py:80} INFO - Job 107: Subtask verificar_threshold
[2023-07-29 03:29:03,730] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T03:23:39.066269+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 03:29:03,858] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=verificar_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T03:23:39.066269+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T03:23:39.066269+00:00
[2023-07-29 03:29:03,882] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 03:29:06,952] {logging_mixin.py:115} INFO - Fallo:  'ascii' codec can't encode character '\xed' in position 59: ordinal not in range(128)
[2023-07-29 03:29:06,955] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_paises.py", line 68, in verificar_threshold
    enviar_alerta(city, categoria_nombre, categoria, min_t, max_t, is_under_threshold=False)
  File "/opt/airflow/dags/script_etl.py", line 130, in enviar_alerta
    raise exception
  File "/opt/airflow/dags/script_etl.py", line 125, in enviar_alerta
    x.sendmail(Variable.get('SMTP_EMAIL_FROM'), Variable.get('SMTP_EMAIL_TO'), message)
  File "/usr/local/lib/python3.7/smtplib.py", line 860, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 59: ordinal not in range(128)
[2023-07-29 03:29:06,982] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_etl_paises, task_id=verificar_threshold, execution_date=20230729T032339, start_date=20230729T032903, end_date=20230729T032906
[2023-07-29 03:29:07,006] {standard_task_runner.py:97} ERROR - Failed to execute job 107 for task verificar_threshold ('ascii' codec can't encode character '\xed' in position 59: ordinal not in range(128); 8412)
[2023-07-29 03:29:07,042] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-29 03:29:07,121] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
