[2023-07-29 02:15:59,100] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:10:54.739595+00:00 [queued]>
[2023-07-29 02:15:59,120] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:10:54.739595+00:00 [queued]>
[2023-07-29 02:15:59,122] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 02:15:59,124] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-07-29 02:15:59,126] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 02:15:59,154] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_threshold> on 2023-07-29 02:10:54.739595+00:00
[2023-07-29 02:15:59,162] {standard_task_runner.py:52} INFO - Started process 3829 to run task
[2023-07-29 02:15:59,173] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'verificar_threshold', 'manual__2023-07-29T02:10:54.739595+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmp56h4w38w', '--error-file', '/tmp/tmp0g1sd_8v']
[2023-07-29 02:15:59,176] {standard_task_runner.py:80} INFO - Job 82: Subtask verificar_threshold
[2023-07-29 02:15:59,341] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:10:54.739595+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 02:15:59,550] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=verificar_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T02:10:54.739595+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T02:10:54.739595+00:00
[2023-07-29 02:15:59,581] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 02:16:00,610] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_paises.py", line 44, in verificar_threshold
    with open('ruta_del_archivo_config.json', 'r') as json_config:
FileNotFoundError: [Errno 2] No such file or directory: 'ruta_del_archivo_config.json'
[2023-07-29 02:16:00,647] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_etl_paises, task_id=verificar_threshold, execution_date=20230729T021054, start_date=20230729T021559, end_date=20230729T021600
[2023-07-29 02:16:00,672] {standard_task_runner.py:97} ERROR - Failed to execute job 82 for task verificar_threshold ([Errno 2] No such file or directory: 'ruta_del_archivo_config.json'; 3829)
[2023-07-29 02:16:00,733] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-29 02:16:00,808] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
