[2023-07-26 17:37:10,291] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T17:36:54.606182+00:00 [queued]>
[2023-07-26 17:37:10,311] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T17:36:54.606182+00:00 [queued]>
[2023-07-26 17:37:10,314] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 17:37:10,317] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 17:37:10,320] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 17:37:10,371] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_datos> on 2023-07-26 17:36:54.606182+00:00
[2023-07-26 17:37:10,390] {standard_task_runner.py:52} INFO - Started process 330 to run task
[2023-07-26 17:37:10,404] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'transformar_datos', 'manual__2023-07-26T17:36:54.606182+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmp8oe3ackb', '--error-file', '/tmp/tmp5w96yymn']
[2023-07-26 17:37:10,412] {standard_task_runner.py:80} INFO - Job 91: Subtask transformar_datos
[2023-07-26 17:37:10,548] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T17:36:54.606182+00:00 [running]> on host 484a5a9deba0
[2023-07-26 17:37:10,711] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=transformar_datos
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T17:36:54.606182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-26T17:36:54.606182+00:00
[2023-07-26 17:39:04,797] {python.py:173} INFO - Done. Returned value was: name       ciudad  Housing  ... Outdoors               process_date
0          Aarhus  #f3c32c  ...  #f1351b 2023-07-26 17:39:04.785057
1          Aarhus   6.1315  ...     4.13 2023-07-26 17:39:04.785057
2        Adelaide  #f3c32c  ...  #f1351b 2023-07-26 17:39:04.785057
3        Adelaide   6.3095  ...    5.531 2023-07-26 17:39:04.785057
4     Albuquerque  #f3c32c  ...  #f1351b 2023-07-26 17:39:04.785057
..            ...      ...  ...      ...                        ...
527       Yerevan   9.6945  ...   7.7765 2023-07-26 17:39:04.785057
528        Zagreb  #f3c32c  ...  #f1351b 2023-07-26 17:39:04.785057
529        Zagreb     8.91  ...    4.809 2023-07-26 17:39:04.785057
530        Zurich  #f3c32c  ...  #f1351b 2023-07-26 17:39:04.785057
531        Zurich    1.473  ...    5.401 2023-07-26 17:39:04.785057

[532 rows x 19 columns]
[2023-07-26 17:39:04,895] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-07-26 17:39:04,906] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-07-26 17:39:04,940] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_con_conexion_postgres, task_id=transformar_datos, execution_date=20230726T173654, start_date=20230726T173710, end_date=20230726T173904
[2023-07-26 17:39:04,992] {standard_task_runner.py:97} ERROR - Failed to execute job 91 for task transformar_datos (Object of type DataFrame is not JSON serializable; 330)
[2023-07-26 17:39:05,016] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 17:39:05,081] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
