[2023-07-26 19:05:12,974] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T19:05:00.565107+00:00 [queued]>
[2023-07-26 19:05:12,993] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T19:05:00.565107+00:00 [queued]>
[2023-07-26 19:05:12,997] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 19:05:13,000] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 19:05:13,002] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 19:05:13,042] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_datos> on 2023-07-26 19:05:00.565107+00:00
[2023-07-26 19:05:13,050] {standard_task_runner.py:52} INFO - Started process 1735 to run task
[2023-07-26 19:05:13,062] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'transformar_datos', 'manual__2023-07-26T19:05:00.565107+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmp4q2k_5fg', '--error-file', '/tmp/tmpv2rbd_4a']
[2023-07-26 19:05:13,066] {standard_task_runner.py:80} INFO - Job 106: Subtask transformar_datos
[2023-07-26 19:05:13,209] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.transformar_datos manual__2023-07-26T19:05:00.565107+00:00 [running]> on host 484a5a9deba0
[2023-07-26 19:05:13,364] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=transformar_datos
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T19:05:00.565107+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-26T19:05:00.565107+00:00
[2023-07-26 19:06:45,057] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-26 19:06:45,060] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/script_etl.py", line 71, in transform_data
    cursor = connection.cursor()
AttributeError: 'Connection' object has no attribute 'cursor'
[2023-07-26 19:06:45,085] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_con_conexion_postgres, task_id=transformar_datos, execution_date=20230726T190500, start_date=20230726T190512, end_date=20230726T190645
[2023-07-26 19:06:45,121] {standard_task_runner.py:97} ERROR - Failed to execute job 106 for task transformar_datos ('Connection' object has no attribute 'cursor'; 1735)
[2023-07-26 19:06:45,163] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 19:06:45,217] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
