[2023-07-29 02:37:11,276] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:31:58.491153+00:00 [queued]>
[2023-07-29 02:37:11,295] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:31:58.491153+00:00 [queued]>
[2023-07-29 02:37:11,297] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 02:37:11,299] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-07-29 02:37:11,302] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-29 02:37:11,329] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_threshold> on 2023-07-29 02:31:58.491153+00:00
[2023-07-29 02:37:11,337] {standard_task_runner.py:52} INFO - Started process 5166 to run task
[2023-07-29 02:37:11,348] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_paises', 'verificar_threshold', 'manual__2023-07-29T02:31:58.491153+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_paises.py', '--cfg-path', '/tmp/tmpmhk017zy', '--error-file', '/tmp/tmp5nk8hrmt']
[2023-07-29 02:37:11,352] {standard_task_runner.py:80} INFO - Job 92: Subtask verificar_threshold
[2023-07-29 02:37:11,482] {task_command.py:371} INFO - Running <TaskInstance: dag_etl_paises.verificar_threshold manual__2023-07-29T02:31:58.491153+00:00 [running]> on host 068a3bc06d1c
[2023-07-29 02:37:11,621] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Belenpintor
AIRFLOW_CTX_DAG_ID=dag_etl_paises
AIRFLOW_CTX_TASK_ID=verificar_threshold
AIRFLOW_CTX_EXECUTION_DATE=2023-07-29T02:31:58.491153+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-29T02:31:58.491153+00:00
[2023-07-29 02:37:11,649] {base.py:68} INFO - Using connection ID 'redshift_belen' for task execution.
[2023-07-29 02:37:12,666] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl_paises.py", line 44, in verificar_threshold
    with open("config_threshold.json", 'r') as json_config:
FileNotFoundError: [Errno 2] No such file or directory: 'config_threshold.json'
[2023-07-29 02:37:12,693] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_etl_paises, task_id=verificar_threshold, execution_date=20230729T023158, start_date=20230729T023711, end_date=20230729T023712
[2023-07-29 02:37:12,719] {standard_task_runner.py:97} ERROR - Failed to execute job 92 for task verificar_threshold ([Errno 2] No such file or directory: 'config_threshold.json'; 5166)
[2023-07-29 02:37:12,761] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-29 02:37:12,856] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
